# Generated by Django 2.2 on 2022-06-06 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('One_to_many', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bird',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32)),
                ('color', models.CharField(max_length=32)),
            ],
            options={
                'db_table': 'bird',
            },
        ),
    ]
